# live_graph.py
import math
from typing import List, Dict, Any, Optional, Sequence
from PyQt5 import QtWidgets, QtCore
import pyqtgraph as pg
import sys
import random
import datetime

PALETTE = [
    "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd",
    "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf",
]


class LiveGraphWindow(QtWidgets.QDialog):
    """
    GENERATED BY CHATGPT
    Generic, non-blocking live graph window for a list[dict] data source.

    Args:
        data_ref: list of dicts you append to (e.g., GUI.power_data / GUI.sensor_data).
        panels: [
          {"title": "...", "series": [{"key":"field_in_row","name":"Legend Name"}, ...]},
          ...
        ]
        x_mode: "index" (simple) or "timestamp" (expects 'timestamp' string key; uses index here for speed)
        max_points: keep only last N samples in the plotted view for performance
        update_ms: refresh period in milliseconds
    """ 
    def __init__(
        self,
        data_ref: List[Dict[str, Any]],
        panels: Sequence[Dict[str, Any]],
        x_mode: str = "index",
        max_points: Optional[int] = 1000,
        update_ms: int = 300,
        parent=None,
    ):
        super().__init__(parent)
        self.setWindowTitle("Live Graph")
        self.resize(1000, 600)

        self.data_ref = data_ref
        self.panels_cfg = list(panels)
        self.x_mode = x_mode
        self.max_points = max_points

        pg.setConfigOptions(
            background="w",   # white plot background
            foreground="k",   # black axes/labels/legend text & pens
            antialias=True
        )

        self._plots: List[pg.PlotWidget] = []
        self._curves: List[List[pg.PlotDataItem]] = []

        layout = QtWidgets.QVBoxLayout(self)

        for panel in self.panels_cfg:
            plot = pg.PlotWidget(
                title=panel.get("title", ""),
                axisItems={"bottom": pg.DateAxisItem(orientation="bottom")}
            )
            plot.showGrid(x=True, y=True, alpha=0.25)  # light grey grid on white
            legend = plot.addLegend()
            # Make legend frame white with black border
            legend.setBrush("w")
            legend.setPen(pg.mkPen("k"))

            # Black axes + tick labels
            for ax in ("left", "bottom"):
                a = plot.getAxis(ax)
                a.setPen(pg.mkPen("k"))
                a.setTextPen(pg.mkPen("k"))

            curves = []
            for idx, s in enumerate(panel.get("series", [])):
                color = PALETTE[idx % len(PALETTE)]
                curve = plot.plot(
                    name=s.get("name", s.get("key", "")),
                    pen=pg.mkPen(color, width=2)   # unique colour per series
                )
                curves.append(curve)

            self._plots.append(plot)
            self._curves.append(curves)
            layout.addWidget(plot)


        self._timer = QtCore.QTimer(self)
        self._timer.timeout.connect(self._refresh)
        self._timer.start(update_ms)

    # ---------- Helpers ----------
    @staticmethod
    def _safe_float(x) -> Optional[float]:
        try:
            return float(x)
        except Exception:
            return None

    @staticmethod
    def _fill_gaps(series: List[Optional[float]], default=0.0) -> List[float]:
        last = default
        out = []
        for v in series:
            if v is None or (isinstance(v, float) and (math.isnan(v) or math.isinf(v))):
                out.append(last)
            else:
                out.append(v)
                last = v
        return out

    # ---------- Core refresh ----------
    def _refresh(self):
        rows = self.data_ref
        if not rows:
            return

        # Efficient tail view
        start_idx = 0
        if self.max_points is not None and len(rows) > self.max_points:
            start_idx = len(rows) - self.max_points
        view = rows[start_idx:]

        # --- X: simple indices (no conversion) ---
        x = list(range(start_idx, start_idx + len(view)))

        # Build labels straight from your JSON timestamps ("HH:mm:ss")
        labels = [str(r.get("timestamp", "")) for r in view]

        # Downsample labels so they don't overlap (aim for ~8 labels)
        if len(labels) > 0:
            step = max(1, len(labels) // 8)
            tick_list = [(start_idx + i, labels[i]) for i in range(0, len(labels), step)]
        else:
            tick_list = []

        # Update each panel
        for plot, curves, panel_cfg in zip(self._plots, self._curves, self.panels_cfg):
            # Set bottom-axis ticks to your timestamp strings
            ax = plot.getAxis("bottom")
            ax.setTicks([tick_list])  # major ticks only, exact labels from JSON

            series_cfg = panel_cfg.get("series", [])
            for curve, s in zip(curves, series_cfg):
                key = s.get("key")
                vals_raw = [self._safe_float(r.get(key)) for r in view]
                vals = self._fill_gaps(vals_raw, default=0.0)
                curve.setData(x, vals)



# --------------------------
# Self-test / Simulation
# --------------------------
class _SimFeeder(QtCore.QObject):
    """
    Lightweight data simulator for testing the LiveGraphWindow standalone.
    Periodically appends rows into the provided list[dict].
    """
    def __init__(self, data_ref: List[Dict[str, Any]], kind: str = "power", period_ms: int = 200, parent=None):
        super().__init__(parent)
        self.data_ref = data_ref
        self.kind = kind
        self.t = 0
        self.timer = QtCore.QTimer(self)
        self.timer.timeout.connect(self._tick)
        self.timer.start(period_ms)
        random.seed(108)

        # baselines
        self.v = 15.9  # 4S LiPo pack-ish under light load
        self.i_esp = 0.09
        self.i_pi = 0.55
        self.i_fc = 0.10
        self.i_modem = 0.05

        self.temp = 16.0
        self.ph = 7.6
        self.turb = 5.0
        self.no3 = 0.25
        self.po4 = 0.02

    def _now_iso(self):
        return datetime.datetime.now(datetime.UTC).strftime("%H:%M:%S")


    def _tick(self):
        self.t += 1
        if self.kind == "power":
            # Wiggle currents with some cycles
            self.i_esp  = max(0.05, 0.09 + 0.02 * math.sin(self.t/20.0) + random.uniform(-0.005, 0.005))
            self.i_pi   = max(0.35, 0.55 + 0.10 * math.sin(self.t/30.0) + random.uniform(-0.02, 0.02))
            self.i_fc   = max(0.05, 0.10 + 0.03 * math.sin(self.t/25.0) + random.uniform(-0.01, 0.01))
            self.i_modem= max(0.03, 0.05 + 0.03 * (math.sin(self.t/12.0) > 0) + random.uniform(-0.01, 0.01))
            total_i = self.i_esp + self.i_pi + self.i_fc + self.i_modem

            # Simulate slow voltage sag + tiny ripple
            self.v -= total_i * 0.0005  # very gentle decline
            self.v += 0.01 * math.sin(self.t/15.0)
            self.v = max(12.8, min(16.8, self.v))

            self.data_ref.append({
                "timestamp": self._now_iso(),
                "v_batt": round(self.v, 3),
                "i_esp": round(self.i_esp, 3),
                "i_pi": round(self.i_pi, 3),
                "i_fc": round(self.i_fc, 3),
                "i_modem": round(self.i_modem, 3),
            })
        else:
            # Sensor drift + noise
            self.temp += random.uniform(-0.02, 0.02)
            self.ph   += random.uniform(-0.005, 0.005)
            self.turb += random.uniform(-0.1, 0.1)
            self.no3  += random.uniform(-0.002, 0.002)
            self.po4  += random.uniform(-0.0005, 0.0005)

            self.temp = max(5.0, min(30.0, self.temp))
            self.ph   = max(6.5, min(8.5, self.ph))
            self.turb = max(0.0, min(100.0, self.turb))
            self.no3  = max(0.0, self.no3)
            self.po4  = max(0.0, self.po4)

            self.data_ref.append({
                "timestamp": self._now_iso(),
                "temperature": round(self.temp, 2),
                "ph": round(self.ph, 2),
                "turbidity": round(self.turb, 2),
                "nitrate": round(self.no3, 3),
                "phosphate": round(self.po4, 3),
            })


if __name__ == "__main__":
    """
    Run this file directly to see two demo windows:
      - Power graph (voltage + currents)
      - Sensor graph (water quality + nutrients)
    No MQTT/GUI required—data is simulated locally.
    """
    app = QtWidgets.QApplication(sys.argv)

    power_data: List[Dict[str, Any]] = []
    sensor_data: List[Dict[str, Any]] = []

    # Start simulators
    _sim_power = _SimFeeder(power_data, kind="power", period_ms=200)
    _sim_sensor = _SimFeeder(sensor_data, kind="sensor", period_ms=400)

    # Define panels
    power_panels = [
        {"title": "Battery Voltage (V)", "series": [{"key": "v_batt", "name": "V_batt"}]},
        {"title": "Currents (A)", "series": [
            {"key": "i_esp", "name": "ESP"},
            {"key": "i_pi", "name": "Pi"},
            {"key": "i_fc", "name": "FC"},
            {"key": "i_modem", "name": "Modem"},
        ]},
    ]
    sensor_panels = [
        {"title": "Water Quality", "series": [
            {"key": "turbidity", "name": "Turbidity (NTU)"},
            {"key": "temperature", "name": "Temp (°C)"},
            {"key": "ph", "name": "pH"},
        ]},
        {"title": "Nutrients (mg/L)", "series": [
            {"key": "nitrate", "name": "Nitrate"},
            {"key": "phosphate", "name": "Phosphate"},
        ]},
    ]

    # Launch windows
    power_win = LiveGraphWindow(power_data, power_panels, x_mode="index", max_points=1200, update_ms=250)
    sensor_win = LiveGraphWindow(sensor_data, sensor_panels, x_mode="index", max_points=1200, update_ms=400)
    power_win.setWindowTitle("Live Power Graph (Simulation)")
    sensor_win.setWindowTitle("Live Sensor Graph (Simulation)")
    power_win.show()
    sensor_win.show()

    sys.exit(app.exec_())
